### ISSUE TITLE
I created the config.json file and placed it under the server/src/ directory. The contents are as follows. Is that right?

### ISSUE THREAD

**Issue by ZerRui** [mozilla/voice-web#1291]
{
    "BUCKET_NAME": "xxxxbucket",
    "BUCKET_LOCATION": "xxxxxxxxx",
}
(According to the document HOWTO_S3.md step by step operation, no error.)

**When I click on the uploaded audio, there are the following errors. Where is the problem?**，

Missing credentials in config Error: connect EHOSTUNREACH 169.254.169.254:80
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
/api/v1/zh-TW/clips Missing credentials in config Error: connect EHOSTUNREACH 169.254.169.254:80
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

**Comment by Gregoor** [comment]
Hi, sounds like your AWS credentials might be missing. Did you follow these steps as well:
https://github.com/mozilla/voice-web/blob/master/docs/HOWTO_S3.md#install-and-configure-the-aws-command-line-ui
?
