### ISSUE TITLE
login page is empty when build with docker-compose

### ISSUE THREAD

**Issue by d2sys** [mozilla/voice-web#1746]
I downloaded the repository, and try to run docker-compose up.
The site is built and could be seen at the specified port (9000) but the login page is empty,
 actually, I see the next line:
`{"message":""}`

Is it ok? How can I activate profiles management?

**Comment by yohanjk** [comment]
I am also facing same issue. Following is the backend error log
```
[BE] /login next is not a function TypeError: next is not a function 
[BE]     at attempt (/code/node_modules/passport/lib/middleware/authenticate.js:186:32)
[BE]     at authenticate (/code/node_modules/passport/lib/middleware/authenticate.js:362:7)
[BE]     at router.get (/code/server/src/auth-router.ts:132:12)
[BE]     at handleReturn (/code/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
[BE]     at /code/node_modules/express-promise-router/lib/express-promise-router.js:56:9
[BE]     at handleReturn (/code/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
[BE]     at /code/node_modules/express-promise-router/lib/express-promise-router.js:56:9
[BE]     at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
[BE]     at next (/code/node_modules/express/lib/router/route.js:137:13)
[BE]     at Route.dispatch (/code/node_modules/express/lib/router/route.js:112:3)
[BE]     at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
[BE]     at /code/node_modules/express/lib/router/index.js:281:22
[BE]     at Function.process_params (/code/node_modules/express/lib/router/index.js:335:12)
[BE]     at next (/code/node_modules/express/lib/router/index.js:275:10)
[BE]     at SessionStrategy.strategy.pass (/code/node_modules/passport/lib/middleware/authenticate.js:338:9)
[BE]     at SessionStrategy.authenticate (/code/node_modules/passport/lib/strategies/session.js:75:10)
[BE]     at attempt (/code/node_modules/passport/lib/middleware/authenticate.js:361:16)
[BE]     at authenticate (/code/node_modules/passport/lib/middleware/authenticate.js:362:7)
[BE]     at handleReturn (/code/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
[BE]     at /code/node_modules/express-promise-router/lib/express-promise-router.js:56:9
[BE]     at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
[BE]     at trim_prefix (/code/node_modules/express/lib/router/index.js:317:13)
```

There is mention about this in [here](https://discourse.mozilla.org/t/instructions-for-login-config-when-running-common-voice-locally/34025) already

**Comment by Gregoor** [comment]
Thanks for the report! I'll add some docs on setting up login locally.
