### ISSUE TITLE
Bug with en_1085h_2019-06-12" release of Common Voice

### ISSUE THREAD

**Issue by akhilvasvani** [mozilla/voice-web#2075]
I am trying to convert the .mp3 and .tsv files in common voice 2 to .csv files using the 'import_cv2.py' file for DeepSpeech.

I used the command (alphabet textfile, the mp3 files, and tsv files are all in the clips folder (as per the instructions on the main page):
```
python3 bin/import_cv2.py --filter_alphabet data/alphabet.txt data/CV/en/
```
and got back
```
Importing mp3 files...
Traceback (most recent call last):
  File "bin/import_cv2.py", line 166, in <module>
    _preprocess_data(PARAMS.tsv_dir, AUDIO_DIR, label_filter_fun, PARAMS.space_after_every_character)
  File "bin/import_cv2.py", line 43, in _preprocess_data
    _maybe_convert_set(input_tsv, audio_dir, label_filter, space_after_every_character)
  File "bin/import_cv2.py", line 101, in _maybe_convert_set
    for i, _ in enumerate(pool.imap_unordered(one_sample, samples), start=1):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "bin/import_cv2.py", line 72, in one_sample
    _maybe_convert_wav(mp3_filename, wav_filename)
  File "bin/import_cv2.py", line 135, in _maybe_convert_wav
    transformer.build(mp3_filename, wav_filename)
  File "/home/akhil/PycharmProjects/DeepSpeech/venv/lib/python3.6/site-packages/sox/transform.py", line 412, in build
    file_info.validate_input_file(input_filepath)
  File "/home/akhil/PycharmProjects/DeepSpeech/venv/lib/python3.6/site-packages/sox/file_info.py", line 215, in validate_input_file
    "input_filepath {} does not exist.".format(input_filepath)
OSError: input_filepath data/CV/en/clips/36e1606224ac9671de8435737cd8828fc910b8f841de83ef421b
```

I have already posted on the DeepSpeech issue page, but after further discussion with the team there we diagnosed that the problem is with the recent "en_1085h_2019-06-12" release of Common Voice. 

As for proof here is what I can offer:
```
akhil@Minerva:~/DeepSpeech/data/CV/en/clips$ locate 36e1606224ac9671de8435737cd8828fc910b8f841de83ef421be74b734248b5f52477269d8c768705059b4c6fa4ff9c62d802155f249b56de536f33eb90017d.mp3
akhil@Minerva:~/DeepSpeech/data/CV/en/clips$ locate 2cebb7196b292b57a1a2141c4fada2a62318ec53e5deb07a30c89a8bbabfabc2925be2d7159791f8c34f0a9b6f2bd8425a473a9d96f0fefc9054602c084755f7.mp3
/home/akhil/DeepSpeech/data/CV/en/clips/2cebb7196b292b57a1a2141c4fada2a62318ec53e5deb07a30c89a8bbabfabc2925be2d7159791f8c34f0a9b6f2bd8425a473a9d96f0fefc9054602c084755f7.mp3
akhil@Minerva:~/DeepSpeech/data/CV/en/clips$
```

So it does not find the missing file. I located another file just for comparison. And in the first row of the 'train.tsv' file:
client id | path

2cd9a591b669f14a0b7c039f087c902dc075c19a1be9bb23c8e0fecff255f5be36fb3d72c118c972c00def21b62b1df550f2205eaea066cfb70ef4f4f4e152f7 | 36e1606224ac9671de8435737cd8828fc910b8f841de83ef421be74b734248b5f52477269d8c768705059b4c6fa4ff9c62d802155f249b56de536f33eb90017d
-- | --

If possible, could you fix this bug?

**Comment by Gregoor** [comment]
Thanks for the report, I'll look into this soon!

**Comment by Gregoor** [comment]
did the new release fix it for you?

**Comment by akhilvasvani** [comment]
No, @Gregoor it did not

**Comment by ftyers** [comment]
Closing as stale.
