### ISSUE TITLE
Unable to connect to collector

### ISSUE THREAD

**Issue by aryamanpuri** [mozilla/voice-web#2584]
I am getting an error on `docker-compose up` 
```
New Relic for Node.js halted startup due to an error:
web        | [BE] Error: Failed to connect to collector
web        | [BE]     at onStartConnect (/code/node_modules/newrelic/lib/agent.js:237:18)
web        | [BE]     at retry (/code/node_modules/newrelic/lib/collector/api.js:110:14)
web        | [BE]     at onPreConnect (/code/node_modules/newrelic/lib/collector/api.js:162:14)
web        | [BE]     at Immediate.setImmediate (/code/node_modules/newrelic/lib/collector/parse-response.js:62:24)
web        | [BE]     at runCallback (timers.js:705:18)
web        | [BE]     at tryOnImmediate (timers.js:676:5)
web        | [BE]     at processImmediate (timers.js:658:5)
web        | [BE]     at process.topLevelDomainCallback (domain.js:126:23)
web        | [FE] Built!
```
Due to which I am having blank page on `/speak`.

**Comment by MichaelKohler** [comment]
NewRelic doesn't need to be set up on local development environments. The NewRelic startup error can safely be ignored. This error looks like a follow up error from enabling NewRelic without everything that is needed.
