### ISSUE TITLE
Blank sentences on the "Speak" page after the privacy policy is declined

### ISSUE THREAD

**Issue by paulsilaghi** [mozilla/voice-web#259]
- Chrome 59, Firefox 54
- Win 10, iOS 10.3.3/iphone 6S

[Steps to reproduce]:
1. Open https://voice.allizom.org/
2. Go to the "Speak" page
3. Complete 3 recordings
4. Press the 'Submit' button
5. Decline the privacy policy
6. Delete the recordings
7. Go to the "Speak" page and try to complete 3 recordings again

[Expected result]:
- all 3 sentences are displayed correctly

[Actual result]:
- 1st sentence displayed correctly, 2nd and 3rd are blank

![blank sentences](https://user-images.githubusercontent.com/29535384/27734321-0105eafc-5da3-11e7-9f7f-6a8e07f15c85.png)

**Comment by ayushbansal07** [comment]
Hi, I want to work on this issue. But, I am not able to run the webapp on my local machine. 
I cloned your repo. Ran these 2 commands successfully - 
npm install
npm install -g gulp
But when I run gulp, I get this error:

const APP_NAME = 'common-voice';
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

To resolve this, I removed the line 'use strict' from gulpfile.js, but then I got the following error:

let gulp = require('gulp-help')(require('gulp'));
    ^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

Please Help Me Out.

**Comment by mikehenrty** [comment]
Hi @ayushbansal07, this sounds like a nodejs version issue. What version of node do you use? If it's an older one, would you try upgrading to node v7 or v8?
