### ISSUE TITLE
[error] Range request exceeds file boundaries

### ISSUE THREAD

**Issue by gozer** [mozilla/voice-web#309]
Seeing a good chunk of these in production. Not sure how bad that is, but reporting.

```
Range request exceeds file boundaries, goes until byte no 524287 against file size of 110274 bytes
Error: Range request present but invalid, might serve whole file instead
    at Server.respondNoGzip (/var/www/voice/node_modules/node-static/lib/node-static.js:300:23)
    at Server.respond (/var/www/voice/node_modules/node-static/lib/node-static.js:354:14)
    at /var/www/voice/node_modules/node-static/lib/node-static.js:146:22
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by mikehenrty** [comment]
We no longer use node-static, so probably don't see this error in prod anymore.
