### ISSUE TITLE
[error] Could not read from s3

### ISSUE THREAD

**Issue by gozer** [mozilla/voice-web#316]
Seen in prod

```
Could not read from s3 9460bac7-1771-4fb3-aad6-4d83b96129e0/d65c9692c8ff9a4e9ef89464e51beba22b73dbb922758c2cdb20724adbe4fec4.txt { InternalError: We encountered an internal error. Please try again.
    at Request.extractError (/var/www/voice/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (/var/www/voice/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/www/voice/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/www/voice/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/www/voice/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/www/voice/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/www/voice/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/www/voice/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/www/voice/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/www/voice/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/var/www/voice/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/www/voice/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/www/voice/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/www/voice/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/www/voice/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/www/voice/node_modules/aws-sdk/lib/request.js:38:9)
  message: 'We encountered an internal error. Please try again.',
  code: 'InternalError',
  region: null,
  time: 2017-07-21T14:43:01.607Z,
  requestId: '3665842C100DFC9B',
  extendedRequestId: 'dxG0gyeMxwKoHW/h0UcEzLvstRnOpHlue+LCmPh1EUW8S3H+jPqD38t8F0rHEnIsocphqBE+WB0=',
  cfId: undefined,
  statusCode: 500,
  retryable: true }
```

**Comment by mikehenrty** [comment]
This error is most likely coming from amazon, and there is nothing we can do to prevent it. Since we are also, trapping and [handling this on our side](https://github.com/mozilla/voice-web/blob/ef6b8e1770819cc1d7ee517fe54f1fbb2d923f75/server/src/lib/files.ts#L51), I am going to close this and say we do everything we can.
