### ISSUE TITLE
[error] error fetching sentence

### ISSUE THREAD

**Issue by gozer** [mozilla/voice-web#317]
Seen in prod:

```
error fetching sentence { InternalError: We encountered an internal error. Please try again.
    at Request.extractError (/var/www/voice/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (/var/www/voice/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/www/voice/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/www/voice/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/www/voice/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/www/voice/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/www/voice/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/www/voice/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/www/voice/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/www/voice/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/var/www/voice/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/www/voice/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/www/voice/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/www/voice/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/www/voice/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/www/voice/node_modules/aws-sdk/lib/request.js:38:9)
  message: 'We encountered an internal error. Please try again.',
  code: 'InternalError',
  region: null,
  time: 2017-07-21T14:43:01.607Z,
  requestId: '3665842C100DFC9B',
```

**Comment by mikehenrty** [comment]
Amazon gives us errors from time to time, and here we are handling one of these errors. I believe we are doing all we can here for now.
