### ISSUE TITLE
Installing on a mac causes  a bcrypt error with nodejs v10

### ISSUE THREAD

**Issue by mrchrisadams** [mozilla/voice-web#993]
Hi there,

I've just tried setting up the voice-web project, so I can work on #602, and when running `yarn install` on my macbook, I get an error down to there being no downloadable binary of bcrypt available for nodejs v10.

After checking on the nodejs website, this isn't the latest LTS version, but node v10 _is_ the version that's currently installed with when you `brew install nodejs` on a mac, so other may come across this issue too when setting up for the first time.

Here's the log output from a failed install:

```
/C/m/voice-web ❯❯❯ yarn install                                                                                                                                                                   master ◼
yarn install v1.6.0
(node:13769) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > db-migrate-plugin-typescript@2.0.0" has incorrect peer dependency "ts-node@^3.3.0".
warning " > downshift@1.30.0" has unmet peer dependency "prop-types@>=15".
warning " > postcss-cssnext@3.0.2" has unmet peer dependency "caniuse-lite@^1.0.30000697".
[5/5] 📃  Building fresh packages...
[-/6] ⢀ waiting...
[2/6] ⢀ fsevents: ^
[3/6] ⢀ bcrypt:                    ^
[-/6] ⢀ waiting...
error /Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@10.0.0 | darwin | x64
node-pre-gyp info check checked for "/Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt/lib/binding/bcrypt_lib.node" (not found)
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.0.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-darwin-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.0.0 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.0.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/Cellar/node/10.0.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/10.0.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/chrisadams/.node-gyp/10.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/chrisadams/.node-gyp/10.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/10.0.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/chrisadams/.node-gyp/10.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.0.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/bcrypt_node.cc:1:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/chrisadams/.node-gyp/10.0.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/chrisadams/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/bcrypt_node.cc:1:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/chrisadams/.node-gyp/10.0.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/chrisadams/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/bcrypt_node.cc:1:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/chrisadams/.node-gyp/10.0.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/chrisadams/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/bcrypt_node.cc:1:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/chrisadams/.node-gyp/10.0.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/chrisadams/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/10.0.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.0.0/bin/node" "/usr/local/Cellar/node/10.0.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/chrisadams/Code/misc/voice-web/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:947:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.0.0/bin/node" "/Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
```

If you run this with node v8, or use nodenev or nvm to explicitly use nodev8, works fine. In my case I resolved this with nodenv:

```
nodenv local 8.9.4
```

I'm not sure any action is needed, as based on this part of the log, it seems to rely on the maintainers of bcrypt making a binary, but tripped me up, and it might do the same to someone else coming to the project:

```
error /Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt

... (snip)

node-pre-gyp info check checked for "/Users/chrisadams/Code/misc/voice-web/node_modules/bcrypt/lib/binding/bcrypt_lib.node" (not found)
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.0.0 (node-v64 ABI) (falling back to source compile with node-gyp)
```

I ran through this with @mikehenrty at the moz global sprint, so I hey may be the other person to speak to about it if.

**Comment by MSupreme1990** [comment]
The same problem, how to solve?

**Comment by Gregoor** [comment]
@MSupreme1990 I just noticed that we don't even use bcrypt anymore, so I dropped that dependency. Can you fetch the most recent version and try again?

**Comment by bsanders343** [comment]
> Solved with
> 
> > node 11.0.0
> 
> > npm 6.4.1
> 
> I removed bcrypt decepence, then I did `npm install,` then `npm audit fix --force` and last `npm i bcrypt`.
> 
> Now bcrypt it's working again and the **error is solved**.

After HOURS of searching, you have solved my problem! Thank you so much! 👍 🥇

**Comment by IPbianco** [comment]
This worked for me too, however it was just enough to remove bcrypt dependency from package.json, run ```npm install``` and then ```npm i bcrypt``` without using the audit fix command

**Comment by jkurei** [comment]
This could also be related to this problem in node-gyp: https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md . I had to run these commands to check and reset the XCode path: 

```
xcode-select -print-path
sudo xcode-select --reset
xcode-select -print-path
```

If the path changed, you know it needed the reset. I also had to also run `xcodebuild -license` to agree to the XCode license. After this I could build no problem (M1 Mac, Node 14.17, NPM 6.14)

I think I found this via https://medium.com/@mrjohnkilonzi/how-to-resolve-no-xcode-or-clt-version-detected-d0cf2b10a750

**Comment by ErtanOzdemir** [comment]
> npm i bcrypt

I was looking for this solution about 1 hour. Thanks a lot 🎊 🥇

**Comment by ErtanOzdemir** [comment]
> Solved with
> 
> > node 11.0.0
> 
> > npm 6.4.1
> 
> I removed bcrypt decepence, then I did `npm install,` then `npm audit fix --force` and last `npm i bcrypt`.
> 
> Now bcrypt it's working again and the **error is solved**.

I was looking for this solution about 1 hour. Thanks a lot 🎊 🥇

**Comment by lzl124631x** [comment]
Came across this on Google. If you are using `nvm`, you can do `nvm install 11`, then `npm install`. You'd better `npm -v > .nvmrc` so that you can pin to the same node/npm version next time using `nvm use`.

**Comment by americanoame** [comment]
solved with 

node v16.19.0

npm  8.19.3

I removed bcrypt decepence, then I did npm install, then npm audit fix --force and last npm i bcrypt.

thnks for the help
